# -*- coding: utf-8 -*-
"""Adetulafakenewsdetector

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQ6GWfv7zZKb7ZIllmR9M6Sk8DPtmobi
"""

pip install --upgrade tensorflow-gpu==2.11.0

!pip install plotly
!pip install --upgrade nbformat

!pip install nltk
!pip install spacy #spacy is an open-sourse software library for advanced natural language processing
!pip install WordCloud
!pip install gensim # Gensim is an open-source library for unsupervised topic modeling and natural language

import nltk
nltk.download('punkt')

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# load the data
df_true = pd.read_csv("True.csv")
df_fake = pd.read_csv("Fake.csv")

df_true

df_fake

