# -*- coding: utf-8 -*-
"""AdetulaFacialreco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oiq3sgI2zeuS9VNxpX9vgABNiyUDcKlu
"""

pip install pandas scikit-learn opencv-python

import os
import cv2
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import tarfile
import matplotlib.pyplot as plt

tar_file_path = "/content/lfw.tar"

# Create a directory to extract the images
extracted_images_folder = "extracted_images_folder"
os.makedirs(extracted_images_folder, exist_ok=True)

# Extract the tar file
with tarfile.open(tar_file_path, "r") as tar:
    tar.extractall(path=extracted_images_folder)

# Path to the folder containing the extracted facial images (JPEG files)
image_folder = extracted_images_folder

# Loop through the images in the folder and display/print them
for filename in os.listdir(image_folder):
    if filename.endswith(".jpg") or filename.endswith(".jpeg"):
        image_path = os.path.join(image_folder, filename)
        image = cv2.imread(image_path)

        # Display the image
        cv2.imshow(filename, image)

