# -*- coding: utf-8 -*-
"""Adetula pneu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AEdO9LBL5mwAMZTeszNc9rgiluFPuwFf
"""

!pip install kaggle

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

import os
cwd = os.getcwd()
print(cwd)

import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content'

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip chest-xray-pneumonia.zip

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
train_data = train_datagen.flow_from_directory('chest_xray/train', target_size=(150, 150), batch_size=5000, class_mode='binary')
test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)
test_data = test_datagen.flow_from_directory('chest_xray/test', target_size=(150, 150), batch_size=600, class_mode='binary')

# Get the training data
X_train, y_train = next(train_data)

# Get the test data
X_test, y_test = next(test_data)

L_grid = 15
W_grid = 15
figs ,axes = plt.subplots(L_grid ,W_grid ,figsize = (25,25))
axes = axes.ravel()
n_training = len(X_train)
for i in np.arange(0, L_grid*W_grid):
  index = np.random.randint(0,n_training)
  axes[i].imshow(X_train[index])

